//! Drive the LCD screens on a Corne Max over raw HID.

use cornelcd::proto::{Cmd, Half, Keyboard, Screen};
use cornelcd::{activity, anim, clawd, proto, render, screens, usage};
#[cfg(target_os = "linux")]
use cornelcd::sysinfo;
use std::process::ExitCode;
use std::thread::sleep;
use std::time::Duration;

const USAGE: &str = "\
cornelcd — drive the Corne Max LCD screens

USAGE:
    cornelcd <COMMAND>

COMMANDS:
    clock               Switch to the clock screen and keep the time updated
    stats               Switch to the PC-stats screen and feed CPU/GPU/RAM
    screen <0-4>        Switch screens and exit
                          0 WPM+layer  1 PC stats  2 clock
                          3 now-playing  4 gif
    text <string>       Set the now-playing label (screen 3)
    probe               Show which HID interfaces were found, then exit

OPTIONS:
    --half <master|slave|both>   Which screen to target (default: both)
    --interval <seconds>         Update period for clock/stats (default: 1)
";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() || args[0] == "-h" || args[0] == "--help" {
        print!("{USAGE}");
        return Ok(());
    }

    let halves = parse_halves(&args)?;
    let interval = parse_interval(&args)?;

    match args[0].as_str() {
        "probe" => return probe(),
        "testimg" => {
            // Proves the _IMG_FS path end to end: build a raw RGB565 frame,
            // push it, commit it. Vertical colour bands so a wrong stride or
            // byte order is obvious at a glance rather than subtly wrong.
            let mut fb = vec![0u8; proto::FB_LEN];
            for y in 0..proto::SCREEN_H {
                for x in 0..proto::SCREEN_W {
                    let (r, g, b) = match x * 4 / proto::SCREEN_W {
                        0 => (0xFF, 0x00, 0x00),
                        1 => (0x00, 0xFF, 0x00),
                        2 => (0x00, 0x00, 0xFF),
                        _ => (0xD9, 0x77, 0x57), // Claude orange
                    };
                    let px = rgb565(r, g, b);
                    let o = (y * proto::SCREEN_W + x) * 2;
                    // Big-endian: the panel reads the high byte first.
                    fb[o] = (px >> 8) as u8;
                    fb[o + 1] = (px & 0xFF) as u8;
                }
            }

            let kb = Keyboard::open()?;
            let t = std::time::Instant::now();
            for h in &halves {
                let n = kb.push_image(Cmd::ImgFs, *h, &fb, None)?;
                kb.commit_image(*h, Cmd::ImgFs)?;
                println!("pushed {n} chunks ({} bytes) to {h:?}", fb.len());
            }
            println!("took {:.2}s", t.elapsed().as_secs_f32());
        }
        "blink" => {
            // Diagnostic: does a panel accept *repeated* updates, or only the
            // first one? Alternates two solid colours several times.
            let kb = Keyboard::open()?;
            let colors = [0xFF_00_00u32, 0x00_00_FF];
            for round in 0..6 {
                let mut fb = render::Framebuffer::new();
                fb.fill(colors[round % 2]);
                fb.text_centered(70, &format!("{round}"), 0xFFFFFF, 3);
                let t = std::time::Instant::now();
                for h in &halves {
                    kb.push_image(Cmd::ImgFs, *h, &fb.data, None)?;
                    kb.commit_image(*h, Cmd::ImgFs)?;
                }
                println!(
                    "round {round}: {} in {:.2}s",
                    if round % 2 == 0 { "RED" } else { "BLUE" },
                    t.elapsed().as_secs_f32()
                );
                sleep(Duration::from_millis(700));
            }
        }
        "gensprite" => {
            // Emit Clawd's poses as LVGL image descriptors for the firmware.
            // LV_COLOR_DEPTH is 16 with LV_COLOR_16_SWAP=1, so colour bytes go
            // out high-byte-first; TRUE_COLOR_ALPHA adds one alpha byte.
            use clawd::Legs;
            let poses: [(usize, Legs, bool, &str); 8] = [
                (0, Legs::Stand, false, "stand_r"),
                (0, Legs::RunA, false, "run_a_r"),
                (1, Legs::RunB, false, "run_b_r"),
                (1, Legs::Tuck, false, "tuck_r"),
                (0, Legs::Stand, true, "stand_l"),
                (0, Legs::RunA, true, "run_a_l"),
                (1, Legs::RunB, true, "run_b_l"),
                (1, Legs::Tuck, true, "tuck_l"),
            ];

            println!("// Generated by `cornelcd gensprite` — do not edit.");
            println!("// Clawd sprite data originates from the Claude Code binary");
            println!("// (CLAWD_FRAMES / CLAWD_PAL). 16x14, LV_IMG_CF_TRUE_COLOR_ALPHA.");
            println!("\n#include \"clawd_gfx.h\"\n");

            // Pre-scaled, so the firmware blits 1:1 with no LVGL zoom transform.
            let sc = parse_num(&args, "--scale", 4.0)? as usize;

            for (base, legs, mirror, name) in poses {
                let grid = clawd::pose(base, legs, mirror);
                let mut bytes = Vec::new();
                for line in &grid {
                    for _ in 0..sc {
                        for ch in line.chars() {
                            let px = clawd::pal_pub(ch).map(render::rgb565);
                            for _ in 0..sc {
                                match px {
                                    Some(p) => {
                                        bytes.push((p >> 8) as u8); // LV_COLOR_16_SWAP
                                        bytes.push((p & 0xFF) as u8);
                                        bytes.push(0xFF);
                                    }
                                    None => bytes.extend_from_slice(&[0, 0, 0]),
                                }
                            }
                        }
                    }
                }
                println!("static const uint8_t clawd_px_{name}[] = {{");
                for row in bytes.chunks(24) {
                    let s: Vec<String> = row.iter().map(|b| format!("0x{b:02X}")).collect();
                    println!("    {},", s.join(", "));
                }
                println!("}};");
                println!("const lv_img_dsc_t clawd_{name} = {{");
                println!("    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,");
                println!("    .header.always_zero = 0,");
                println!("    .header.w = {}, .header.h = {},", clawd::W * sc as i32, clawd::H * sc as i32);
                println!("    .data_size = {},", bytes.len());
                println!("    .data = clawd_px_{name},");
                println!("}};\n");
            }

            // Activity poses: paint reuses the stock frames, the rest are
            // literal grids in clawd::EXTRA_FRAMES.
            let mut extra_names: Vec<String> = Vec::new();
            let painted: [(usize, &str); 2] = [(0, "paint_a"), (1, "paint_b")];
            for (base, name) in painted {
                let grid = clawd::pose(base, Legs::Stand, false);
                emit_pose(&grid, name, sc);
                extra_names.push(name.to_string());
            }
            for (name, rows) in clawd::EXTRA_FRAMES {
                let grid: Vec<String> = rows.iter().map(|r| r.to_string()).collect();
                emit_pose(&grid, name, sc);
                extra_names.push(name.to_string());
            }

            println!("const lv_img_dsc_t *const clawd_poses[CLAWD_POSE_COUNT] = {{");
            for (_, _, _, name) in poses {
                println!("    &clawd_{name},");
            }
            for name in &extra_names {
                println!("    &clawd_{name},");
            }
            println!("}};");
        }
        "bench" => {
            // Cost is chunks-per-step; the wire does ~1 chunk per USB frame,
            // measured at 1024 chunks in 1.02s. No hardware needed for this.
            const MS_PER_CHUNK: f32 = 1.0;
            for scale in [2, 3, 4] {
                let steps = anim::jump_sequence(anim::Dir::LeftToRight, scale, false);
                let mut prev: std::collections::HashMap<u8, render::Framebuffer> =
                    std::collections::HashMap::new();
                let mut counts = Vec::new();

                for s in &steps {
                    let key = s.half as u8;
                    let n = match prev.get(&key) {
                        Some(p) => s.fb.diff_chunks(p).len(),
                        None => proto::FB_LEN.div_ceil(25),
                    };
                    counts.push(n);
                    prev.insert(key, render::Framebuffer { data: s.fb.data.clone() });
                }

                // Skip the two initial full pushes when judging the run itself.
                let moving: Vec<usize> =
                    counts.iter().copied().filter(|&n| n < 1000).collect();
                let avg = moving.iter().sum::<usize>() as f32 / moving.len().max(1) as f32;
                let worst = moving.iter().copied().max().unwrap_or(0);

                println!(
                    "scale {scale}x ({}x{} px): {} steps, avg {:.0} chunks/step, worst {worst}",
                    clawd::W * scale,
                    clawd::H * scale,
                    steps.len(),
                    avg,
                );
                println!(
                    "            -> {:.1} fps avg, {:.1} fps worst case, {:.1}s for the whole jump",
                    1000.0 / (avg * MS_PER_CHUNK),
                    1000.0 / (worst as f32 * MS_PER_CHUNK),
                    counts.iter().sum::<usize>() as f32 * MS_PER_CHUNK / 1000.0,
                );
            }
        }
        "usage" => {
            let t = usage::collect()?;
            println!(
                "session {} — {} billable ({} in, {} out, {} cache-read)",
                t.session_name,
                usage::short(t.session.billable()),
                usage::short(t.session.input + t.session.cache_write),
                usage::short(t.session.output),
                usage::short(t.session.cache_read),
            );
            println!(
                "7 days  — {} billable across {} transcript(s)",
                usage::short(t.week.billable()),
                t.files_scanned
            );
        }
        "clawd" => {
            // One-shot: place Clawd at a position/pose. For stepping through
            // the animation by hand.
            let x = parse_num(&args, "--x", 8.0)? as i16;
            let pose = parse_num(&args, "--pose", 0.0)? as u8;
            let lift = parse_num(&args, "--lift", 0.0)? as u8;
            let hide = args.iter().any(|a| a == "--hide");
            let kb = Keyboard::open()?;
            for h in &halves {
                kb.set_clawd(*h, x, pose, lift, !hide)?;
            }
            println!("clawd x={x} pose={pose} lift={lift} visible={}", !hide);
        }
        "claude" => {
            let kb = Keyboard::open()?;
            run_watch(&kb, interval)?;
        }
        "watch" => {
            let kb = Keyboard::open()?;
            run_watch(&kb, interval)?;
        }
        "daemon" | "tray" => {
            return cornelcd::run_daemon(interval);
        }
        "activity" => {
            // Print what we would report, without touching the keyboard.
            let mut w = activity::Watcher::new();
            let st = w.poll()?;
            let t = w.tally();
            println!("state: {} ({st})", activity::state_name(st));
            println!("last tool: {:?}", w.last_tool());
            println!("tally: bash={} edit={} write={} web={}", t.bash, t.edit, t.write, t.web);
        }
        "claude-img" => {
            // Legacy host-rendered mode: master panel only, no firmware needed.
            let scale = parse_num(&args, "--scale", 4.0)? as i32;
            let every = Duration::from_secs_f64(parse_num(&args, "--jump-every", 20.0)?);
            let flip = args.iter().any(|a| a == "--flip-landing");
            let kb = Keyboard::open()?;
            run_claude(&kb, interval, scale, every, flip)?;
        }
        "jump" => {
            let scale = parse_num(&args, "--scale", 4.0)? as i32;
            let flip = args.iter().any(|a| a == "--flip-landing");
            let dir = match args.get(1).map(String::as_str) {
                Some("left") => anim::Dir::RightToLeft,
                _ => anim::Dir::LeftToRight,
            };
            let kb = Keyboard::open()?;
            let steps = anim::jump_sequence(dir, scale, flip);
            let t = std::time::Instant::now();
            let mut last: std::collections::HashMap<u8, render::Framebuffer> =
                std::collections::HashMap::new();
            let mut chunks = 0;
            for step in steps {
                chunks += push(&kb, step.half, &step.fb, last.get(&(step.half as u8)))?;
                last.insert(step.half as u8, step.fb);
            }
            println!(
                "{dir:?}: {chunks} chunks in {:.2}s",
                t.elapsed().as_secs_f32()
            );
        }
        "clock" => {
            let kb = Keyboard::open()?;
            for h in &halves {
                kb.set_screen(*h, Screen::Clock)?;
            }
            println!("clock running on {} — ctrl-c to stop", describe(&halves));
            run_clock(&kb, &halves, interval)?;
        }
        #[cfg(target_os = "linux")]
        "stats" => {
            let kb = Keyboard::open()?;
            for h in &halves {
                kb.set_screen(*h, Screen::PcStats)?;
            }
            println!("stats running on {} — ctrl-c to stop", describe(&halves));
            run_stats(&kb, &halves, interval)?;
        }
        "screen" => {
            let n: u8 = args
                .get(1)
                .ok_or("screen needs an id, 0-4")?
                .parse()
                .map_err(|_| "screen id must be a number 0-4")?;
            let screen = Screen::from_id(n).ok_or("screen id must be 0-4")?;
            let kb = Keyboard::open()?;
            for h in &halves {
                kb.set_screen(*h, screen)?;
            }
            println!("set screen {n} ({screen:?}) on {}", describe(&halves));
        }
        "text" => {
            let text = args.get(1).ok_or("text needs a string")?;
            let kb = Keyboard::open()?;
            for h in &halves {
                kb.set_screen(*h, Screen::NowPlaying)?;
                kb.set_now_playing(*h, text)?;
            }
            println!("set text on {}", describe(&halves));
        }
        other => {
            eprintln!("unknown command: {other}\n");
            print!("{USAGE}");
            return Err("unknown command".into());
        }
    }

    Ok(())
}

/// Left half shows usage, right half animates Clawd.
///
/// A full frame is 1024 chunks and takes about a second, so only the chunks
/// that actually changed get pushed. Clawd's body is identical between frames,
/// so the animation touches a small fraction of the screen.
fn run_claude(
    kb: &Keyboard,
    interval: Duration,
    scale: i32,
    jump_every: Duration,
    flip_landing: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let _ = (jump_every, flip_landing);

    // Everything lives on the master panel. The slave cannot take host-pushed
    // pixels without wedging the firmware, so it keeps the firmware's own
    // WPM/layer screen — which is genuinely useful and costs us nothing.
    let half = Half::Master;
    let mut last: Option<render::Framebuffer> = None;

    let mut week_ref: u64 = 0;
    let mut totals = usage::collect()?;
    let mut last_usage_refresh = std::time::Instant::now();

    // Clawd patrols the bottom strip, turning around at each edge.
    let span = proto::SCREEN_W as i32 - clawd::W * scale;
    let stride = 3 * scale;
    let mut x = 0i32;
    let mut going_right = true;
    let mut frame = 0usize;

    println!("claude panel running on the left half — ctrl-c to stop");
    println!("(right half keeps the firmware's WPM/layer screen; see README)");

    loop {
        if last_usage_refresh.elapsed() > Duration::from_secs(30) {
            totals = usage::collect()?;
            last_usage_refresh = std::time::Instant::now();
        }
        week_ref = week_ref.max(totals.week.billable()).max(1);

        // Alternate the leg pose so he actually looks like he's walking.
        let legs = if frame.is_multiple_of(2) {
            clawd::Legs::RunA
        } else {
            clawd::Legs::RunB
        };

        let state = screens::ClawdState {
            x,
            frame: frame % 2,
            legs,
            mirror: !going_right,
            lift: 0,
            scale,
        };

        let fb = screens::usage_screen(&totals, week_ref, Some(&state));
        push(kb, half, &fb, last.as_ref())?;
        last = Some(fb);

        if going_right {
            x += stride;
            if x >= span {
                x = span;
                going_right = false;
            }
        } else {
            x -= stride;
            if x <= 0 {
                x = 0;
                going_right = true;
            }
        }

        frame += 1;
        sleep(interval);
    }
}

#[allow(dead_code)]
fn other_half(h: Half) -> Half {
    match h {
        Half::Master => Half::Slave,
        Half::Slave => Half::Master,
    }
}

/// Push a framebuffer, sending only what changed when we have a previous one.
fn push(
    kb: &Keyboard,
    half: Half,
    fb: &render::Framebuffer,
    prev: Option<&render::Framebuffer>,
) -> Result<usize, Box<dyn std::error::Error>> {
    let n = match prev {
        Some(p) => {
            let changed = fb.diff_chunks(p);
            if changed.is_empty() {
                return Ok(0);
            }
            kb.push_image(Cmd::ImgFs, half, &fb.data, Some(&changed))?
        }
        None => kb.push_image(Cmd::ImgFs, half, &fb.data, None)?,
    };
    kb.commit_image(half, Cmd::ImgFs)?;
    Ok(n)
}

fn run_clock(
    kb: &Keyboard,
    halves: &[Half],
    interval: Duration,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut last = String::new();
    loop {
        let now = chrono::Local::now().format("%H:%M").to_string();
        // The screen only needs a write when the displayed value changes.
        if now != last {
            for h in halves {
                kb.set_time(*h, &now)?;
            }
            last = now;
        }
        sleep(interval);
    }
}

#[cfg(target_os = "linux")]
fn run_stats(
    kb: &Keyboard,
    halves: &[Half],
    interval: Duration,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut prev = sysinfo::read_cpu_times()?;
    loop {
        sleep(interval);

        let now = sysinfo::read_cpu_times()?;
        let cpu = sysinfo::cpu_percent(prev, now);
        prev = now;

        let ram = sysinfo::ram_percent()?;
        let gpu = sysinfo::gpu_percent();

        for h in halves {
            kb.set_gauge(Cmd::Cpu, *h, cpu)?;
            kb.set_gauge(Cmd::Ram, *h, ram)?;
            if let Some(g) = gpu {
                kb.set_gauge(Cmd::Gpu, *h, g)?;
            }
        }
    }
}

fn probe() -> Result<(), Box<dyn std::error::Error>> {
    let api = hidapi::HidApi::new()?;
    let mut found = 0;

    println!("HID interfaces for {:04x}:{:04x}", proto::VID, proto::PID);
    for d in api.device_list() {
        if d.vendor_id() != proto::VID || d.product_id() != proto::PID {
            continue;
        }
        found += 1;
        let raw = d.usage_page() == proto::RAW_USAGE_PAGE && d.usage() == proto::RAW_USAGE;
        println!(
            "  usage_page={:#06x} usage={:#04x} iface={} {} {}",
            d.usage_page(),
            d.usage(),
            d.interface_number(),
            d.path().to_string_lossy(),
            if raw { "  <-- raw HID (this one)" } else { "" }
        );
    }

    if found == 0 {
        println!("  (none — keyboard not connected?)");
    }
    Ok(())
}

fn parse_halves(args: &[String]) -> Result<Vec<Half>, Box<dyn std::error::Error>> {
    let Some(i) = args.iter().position(|a| a == "--half") else {
        return Ok(Half::both().to_vec());
    };
    match args.get(i + 1).map(String::as_str) {
        Some("master") => Ok(vec![Half::Master]),
        Some("slave") => Ok(vec![Half::Slave]),
        Some("both") | None => Ok(Half::both().to_vec()),
        Some(other) => Err(format!("--half must be master, slave or both (got {other})").into()),
    }
}

fn parse_interval(args: &[String]) -> Result<Duration, Box<dyn std::error::Error>> {
    let Some(i) = args.iter().position(|a| a == "--interval") else {
        return Ok(Duration::from_secs(1));
    };
    let secs: f64 = args
        .get(i + 1)
        .ok_or("--interval needs a value in seconds")?
        .parse()
        .map_err(|_| "--interval must be a number")?;
    if secs <= 0.0 {
        return Err("--interval must be positive".into());
    }
    Ok(Duration::from_secs_f64(secs))
}

fn describe(halves: &[Half]) -> String {
    if halves.len() == 2 {
        "both halves".into()
    } else {
        format!("{:?} half", halves[0]).to_lowercase()
    }
}

/// Pack 8-bit RGB into RGB565.
fn rgb565(r: u8, g: u8, b: u8) -> u16 {
    ((r as u16 & 0xF8) << 8) | ((g as u16 & 0xFC) << 3) | (b as u16 >> 3)
}

/// Parse a `--flag <number>` option, falling back to `default`.
fn parse_num(args: &[String], flag: &str, default: f64) -> Result<f64, Box<dyn std::error::Error>> {
    let Some(i) = args.iter().position(|a| a == flag) else {
        return Ok(default);
    };
    args.get(i + 1)
        .ok_or_else(|| format!("{flag} needs a value").into())
        .and_then(|v| {
            v.parse::<f64>()
                .map_err(|_| format!("{flag} must be a number").into())
        })
}

/// Emit one pose as an LVGL image descriptor, scaled by `sc`.
fn emit_pose(grid: &[String], name: &str, sc: usize) {
    let mut bytes = Vec::new();
    for line in grid {
        for _ in 0..sc {
            for ch in line.chars() {
                let px = clawd::pal_pub(ch).map(render::rgb565);
                for _ in 0..sc {
                    match px {
                        Some(p) => {
                            bytes.push((p >> 8) as u8); // LV_COLOR_16_SWAP
                            bytes.push((p & 0xFF) as u8);
                            bytes.push(0xFF);
                        }
                        None => bytes.extend_from_slice(&[0, 0, 0]),
                    }
                }
            }
        }
    }
    println!("static const uint8_t clawd_px_{name}[] = {{");
    for row in bytes.chunks(24) {
        let s: Vec<String> = row.iter().map(|b| format!("0x{b:02X}")).collect();
        println!("    {},", s.join(", "));
    }
    println!("}};");
    println!("const lv_img_dsc_t clawd_{name} = {{");
    println!("    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,");
    println!("    .header.always_zero = 0,");
    println!("    .header.w = {}, .header.h = {},", clawd::W * sc as i32, clawd::H * sc as i32);
    println!("    .data_size = {},", bytes.len());
    println!("    .data = clawd_px_{name},");
    println!("}};\n");
}

/// Report Claude's activity and the tool tally to the keyboard.
///
/// Clawd animates himself; this only tells him *what* to act out. If this
/// process stops, the firmware's watchdog forgets us after 10s and he returns
/// to pacing and jumping on his own.
fn run_watch(kb: &Keyboard, interval: Duration) -> Result<(), Box<dyn std::error::Error>> {
    let mut w = activity::Watcher::new();
    let mut last_state = 255u8;
    let mut last_tally = None;

    println!("watching Claude Code — ctrl-c to stop (clawd runs solo without this)");

    loop {
        let state = w.poll()?;
        if state != last_state {
            kb.set_activity(state)?;
            println!("-> {}", activity::state_name(state));
            last_state = state;
        } else {
            // Keep the watchdog fed even when nothing changes.
            kb.set_activity(state)?;
        }

        let t = w.tally();
        if Some(t) != last_tally {
            let lines = [
                format!("BASH {}", t.bash),
                format!("EDIT {}", t.edit),
                format!("WRITE {}", t.write),
                format!("WEB {}", t.web),
            ];
            for h in Half::both() {
                for (i, line) in lines.iter().enumerate() {
                    kb.set_tally(h, i as u8, line)?;
                }
            }
            last_tally = Some(t);
        }

        sleep(interval);
    }
}
